import React, { Component } from 'react';

export default class AGB extends Component {
    render() {
        return (
            <div class="container">
                <div class="termctn">
                    <p class="legal language">
                            You can find the English version <a class="linkcolor" href="terms">here</a>
                    </p>
                    <br />
                    <p class="header">
                            RichList Term of Service
                    </p>
                    <p class="terms">Last Updated on August 10, 2019</p>

                    <p class="terms">
                    <b>Überblick.</b><br />
                    Willkommen bei der mobilen App RichList ("App") und der zugehörigen Website richlist.net ("Seite"). Auf der gesamten Website beziehen sich "wir", "uns", "unsere", "Service", “Dienste”, "RichList" auf die RichList-Website, -App und alle entsprechenden Dienste. Alle Nutzer dieser Dienste werden als "Benutzer" bezeichnet. <br />
                    <br />
                    Bitte lesen Sie die folgenden Allgemeinen Geschäftsbedingungen sorgfältig durch, bevor Sie die App installieren, herunterladen und/oder verwenden oder diese Website verwenden. Durch den Besuch unserer Website und/oder die Nutzung unserer Dienste/App erklären Sie sich mit den folgenden Allgemeinen Geschäftsbedingungen ("Allgemeinen Geschäftsbedingungen") einverstanden, einschließlich dieser zusätzlichen Bedingungen und Richtlinien, auf die hier verwiesen wird und/oder die über einen Hyperlink verfügbar sind. Diese Allgemeinen Geschäftsbedingungen gelten für alle Benutzer der App, einschließlich, aber nicht ausschließlich, für Benutzer, die Browsende, Kunden, Zahlende und/oder Mitwirkende von Inhalten sind.<br />
                    Wenn Sie nicht einverstanden sind, an diese Bedingungen gebunden zu sein, greifen Sie bitte nicht auf RichList zu oder verwenden Sie es nicht.<br />
                    <br />
                    Die in dieser Vereinbarung verwendeten Überschriften dienen nur der Vereinfachung und werden diese Bedingungen nicht einschränken oder anderweitig beeinflussen.<br />
                    <br />
                    <b>Information.</b><br />
                    Wir sind nicht verantwortlich für die Richtigkeit, Vollständigkeit oder Aktualität der in RichList bereitgestellten Informationen. RichList kann bestimmte historische Informationen enthalten. Historische Informationen sind notwendigerweise nicht aktuell und werden nur zu Referenzzwecken bereitgestellt. Das Material auf RichList dient nur der allgemeinen Information und sollte nicht als alleinige Grundlage für Entscheidungen herangezogen werden, ohne die primären, genaueren, vollständigen oder aktuelleren Informationsquellen zu konsultieren. Das Vertrauen in das Material von RichList erfolgt auf eigenes Risiko. Wir behalten uns das Recht vor, den Inhalt von RichList jederzeit zu ändern, sind jedoch nicht verpflichtet, Informationen von RichList zu aktualisieren. Sie stimmen zu, dass es in Ihrer Verantwortung liegt, Änderungen an RichList zu überwachen. Ihre Verwendung des Inhalts oder eines Teils davon erfolgt ausschließlich auf Ihr eigenes Risiko und Ihre eigene Verantwortung.<br />
                    <br />
                    <b>Änderung.</b><br />
                    Alle neuen Funktionen oder Tools, die zu den Services hinzugefügt werden, unterliegen ebenfalls den Allgemeinen Geschäftsbedingungen. Auf dieser Seite können Sie jederzeit die aktuellste Version der Allgemeinen Geschäftsbedingungen einsehen. Wir behalten uns das Recht vor, Teile dieser Allgemeinen Geschäftsbedingungen zu aktualisieren, zu ändern oder zu ersetzen, indem wir Aktualisierungen und/oder Änderungen an unserer Website veröffentlichen. Es liegt in Ihrer Verantwortung, diese Seite regelmäßig auf Änderungen zu überprüfen. Ihre fortgesetzte Nutzung oder Ihr Zugriff auf die Dienste nach der Veröffentlichung von Änderungen stellt die Annahme dieser Änderungen dar.<br />
                    <br />
                    <b>Unsere Rechte.</b><br />
                    Wir behalten uns diese Rechte vor, die wir jederzeit und nach eigenem Ermessen und ohne Haftung oder Mitteilung an Sie ausüben können (sofern dies nicht durch geltendes Recht verboten ist): (a) Wir können Teile oder die gesamten Dienste und deren Funktionalität ändern; (b) wir können Teile oder die gesamten Dienste aussetzen oder einstellen; (c) wir können Ihren Zugang zu oder die Nutzung von Teilen oder allen Diensten beenden, aussetzen, einschränken oder deaktivieren; (d) wir können den Zugang zu Ihrem Konto oder Teilen beenden, aussetzen, einschränken oder deaktivieren; und (e) wir können unsere Berechtigungskriterien ändern, um die Dienste zu nutzen (und wenn solche Änderungen der Berechtigungskriterien gesetzlich verboten sind, können wir Ihr Recht zur Nutzung der Dienste in dieser Gerichtsbarkeit widerrufen).<br />
                    <br />
                    <b>Berechtigung Bedingungen zu akzeptieren. </b><br />
                    Die Dienste stehen nur Personen zur Verfügung, die (a) entweder (i) für EU Bewohner mindestens sechzehn (16) Jahre alt sind und (ii) für US Bewohner mindestens dreizehn (13) Jahre alt sind; (iii) oder wenn sich eine Person in einem anderen Standort befindet, sie älter ist, als das nach den in Ihrer Gerichtsbarkeit geltenden Gesetzen als "Kind" definiert ist; und (b) die Rechtsfähigkeit besitzen, diese Bedingungen einzugehen und eine nach geltendem Recht verbindliche Vereinbarung zu treffen, oder die erforderliche Einwilligung ihres Erziehungsberechtigten erhalten haben, um diese Bedingungen einzugehen, und vorausgesetzt, Sie sind im Alter zwischen 13 und 18 Jahren erklären Sie, dass Ihr Erziehungsberechtigter diese Bedingungen einschließlich der Datenschutzrichtlinie überprüft und ihnen zugestimmt hat. Sie erklären hiermit, dass Sie die gesetzliche Befugnis besitzen, diese Bedingungen einzugehen, eine verbindliche Vereinbarung nach geltendem Recht zu treffen, die Dienste in Übereinstimmung mit diesen Bedingungen zu nutzen und Ihre Verpflichtungen aus diesen Bedingungen vollständig zu erfüllen. Personen unter einem bestimmten Alter, die die ausdrückliche Zustimmung ihres Erziehungsberechtigten haben, kann die Teilnahme an bestimmten Diensten dennoch untersagt werden.<br />
                    <br />
                    <b>Zugang zu Diensten.</b><br />
                    Solange diese Bedingungen in Kraft sind, erteilen wir Ihnen hiermit die Erlaubnis, die Dienste zu besuchen und zu nutzen, sofern Sie diese Bedingungen und geltendes Recht einhalten.<br />
                    Wir behalten uns das Recht vor, den Service jederzeit aus irgendeinem Grund zu verweigern.<br />
                    <br />
                    <b>Einschränkungen.</b><br />
                    Sie dürfen nicht: (i) Teile der Dienste ohne unsere vorherige schriftliche Genehmigung kopieren, verbreiten oder modifizieren; (ii) Inhalte (nachstehend definiert) verwenden, modifizieren, abgeleitete Werke erstellen, übertragen (durch Verkauf, Weiterverkauf, Lizenzierung, Unterlizenzierung, Download oder auf andere Weise), reproduzieren, verbreiten, anzeigen oder offenlegen, sofern dies nicht ausdrücklich genehmigt ist; (iii) Server oder Netzwerke, die mit den Diensten verbunden sind, stören; (iv) ein automatisiertes System (einschließlich, ohne Einschränkung, "Bots" und "Spiders") verwenden oder starten, um auf die Dienste zuzugreifen oder diese zu nutzen; und/oder (v) umgehen, deaktivieren oder anderweitig beeinträchtigen von sicherheitsrelevante Funktionen der Dienste oder Funktionen, die die Verwendung oder das Kopieren von Inhalten verhindern oder einschränken oder die Nutzung der Dienste einschränken.<br />
                    <br />
                    <b>Konto.</b><br />
                    Um die App nutzen zu können, haben Sie einen zufällig generierten eindeutigen Schlüssel ("Schlüssel"), um identifiziert zu werden. Sie stimmen zu, Ihren Schlüssel nicht weiterzugeben oder den Schlüssel eines anderen Benutzers zu verwenden. Wir behalten uns das Recht vor, Kontoinformationen ohne vorherige Ankündigung zu löschen. Wenn Sie Ihren Schlüssel verlieren, gibt es möglicherweise keine Möglichkeit, Ihre Kontoinformationen oder Ihren Schlüssel abzurufen. Sie sind allein für die mit Ihrem Schlüssel durchgeführten Aktivitäten verantwortlich und müssen Ihren Schlüssel sicher aufbewahren. Wenn Sie Ihren Schlüssel und die entsprechenden Daten löschen möchten, können Sie dies tun, indem Sie eine E-Mail-Anfrage an RichList unter richlistapp(at)gmail.com senden. Wenn Sie ausreichende Nachweise für vergangene Transaktionen vorlegen können, werden wir Ihre Anfrage gemäß den geltenden Gesetzen bearbeiten.<br />
                    <br />
                    <b>Zahlung.</b><br />
                    RichList ermöglicht es dem Benutzer, Geld an uns zu überweisen ("Zahlung") und Sie anerkennen, dass Sie keine Waren/Dienstleistungen als Gegenleistung für diese Zahlung erhalten. Zahlungen können von Benutzern eingereicht und über verschiedene Dienste für Zahlungsverarbeitung von Drittanbietern („ Zahlungsanbieter “) verarbeitet werden. Für diese Zahlungen gelten möglicherweise zusätzliche Bedingungen. Zusätzlich zu diesen Bedingungen erklären Sie sich damit einverstanden, dass die Bedingungen dieser Zahlungsanbieter für die Online-Zahlungen gelten. Aufgrund von Wechselkurs Abweichungen zwischen unserer API und der API der Zahlungsanbieter kann die Gesamtgebühr für den Zahlenden um einen minimalen Betrag abweichen. Wir behalten uns das Recht vor, jederzeit und aus jedem Grund nach eigenem Ermessen: (1) unsere verfügbaren Zahlungsanbieter zu ändern; (2) die Option zur Ausführung von Zahlungen ausschließen; und (3) die Anzahl und/oder Häufigkeit der über die App zulässigen Zahlungsvorgänge zu begrenzen.<br />
                    RichList ist in keinem Fall verantwortlich oder haftbar für: (A) die Verfügbarkeit und/oder den Betrieb eines Zahlungsanbieters; (B) die Bestätigung oder Erfüllung von Transaktionen in unseren Diensten (C) von nicht erfüllten Zahlungstransaktionen, die sich aus falschen Zahlungsinformationen des Nutzers ergeben oder die nicht in Übereinstimmung mit diesen Bedingungen erfolgen. <br />
                    Durch das Anbieten einer Zahlung bestätigen Sie als Benutzer hiermit, dass: (i) Sie eine gültige Kreditkarte verwenden, die Ihnen gehört und vollständige und genaue Informationen im Zusammenhang mit der Transaktion bereitstellen; und (ii) Ihnen keine Waren oder Dienstleistungen als Gegenleistung für die Zahlung angeboten wurden und die Zahlung in keiner Weise angefordert wurde. Alle Zahlungen sind nicht erstattungsfähig und können von den Nutzern nicht zurückgenommen oder rückerstattet werden. Der Benutzer bestätigt und erkennt hiermit an, dass Zahlungen nicht von Gegenleistungen oder Vorteilen abhängig gemacht werden, insbesondere nicht von der Leistung von RichList.<br />
                    <br />
                    <b>Rechte an geistigem Eigentum.</b><br />
                    1. Endbenutzerlizenz. Vorbehaltlich der Bestimmungen dieser Bedingungen gewähren wir Ihnen hiermit eine persönliche, widerrufliche, nicht ausschließliche, nicht unterlizenzierbare, nicht zuweisbare, nicht übertragbare Lizenz („ Lizenz “) zum: (i) Herunterladen, Installieren und Verwenden die App und / oder das Plug-In (sofern zutreffend) auf einem Computer, Mobiltelefon oder einem anderen Gerät, mit dem Sie auf den Dienst zugreifen (das “Gerät“); und (ii) in Übereinstimmung mit diesen Bedingungen auf die Dienste auf diesem Gerät zuzugreifen und diese zu nutzen.<br />
                    2. Inhalte und Marken. Der (i) Inhalt der Dienste, einschließlich, ohne Einschränkung, der Texte, Beschreibungen, Produkte, Software, Grafiken, Fotos, Sounds, Videos, interaktiven Funktionen und Dienste (zusammen die „Materialien“), (ii) und Benutzerbeiträge sind wie nachstehend definiert (zusammen mit den Materialien, die „ Inhalte“) Eigentum von RichList und/oder seinen Lizenzgebern und können durch geltendes Urheberrecht oder andere Gesetze und Verträge zum Schutz geistigen Eigentums geschützt sein. Alle anderen Marken, Dienstleistungsmarken und Logos, die innerhalb der Services verwendet werden sind Marken, Dienstleistungsmarken oder Logos der jeweiligen Eigentümer. Wir behalten uns alle Rechte vor, die nicht ausdrücklich in und an den Diensten und den Inhalten gewährt werden.<br />
                    3. Lizenzbeschränkungen. Sie erklären sich damit einverstanden und gestatten Dritten nicht, (i) die Dienste in Unterlizenz zu vergeben, weiterzugeben, zu verkaufen, zu leasen, zu verleihen oder zu vermieten; (ii) die Dienste über ein Netzwerk verfügbar zu machen, in dem sie von mehreren Geräten genutzt werden können, die verschiedenen Personen gleichzeitig gehören oder von diesen betrieben werden; (iii) den Quellcode der Dienste zu disassemblieren, zurückzuentwickeln, zu dekompilieren, zu entschlüsseln oder zu versuchen, ihn abzuleiten; (iv) Kopieren, Ändern, Verbessern oder Erstellen von abgeleiteten Werken der Dienste oder eines Teils davon; (v) sicherheitsrelevante Funktionen der Dienste zu umgehen, zu deaktivieren oder auf andere Weise zu beeinträchtigen oder Funktionen, die die Nutzung oder das Kopieren von Inhalten verhindern oder einschränken oder die Nutzung der Dienste einschränken; (vi) Entfernen, Ändern oder Verdecken von firmeneigenen Hinweisen oder Kennzeichnungen, einschließlich Urheberrechts-, Marken-, Patent- oder sonstigen Hinweisen, die in oder über die Dienste enthalten sind oder angezeigt werden; (vii) von der App bereitgestellte Kommunikationssysteme verwenden, um nicht autorisierte und/oder nicht angeforderte kommerzielle Kommunikationen zu senden; (viii) Verwenden des RichList-Namens oder -Logos ohne unsere vorherige schriftliche Zustimmung; und/oder (ix) die Dienste verwenden, um gegen geltende Gesetze, Regeln oder Vorschriften zu verstoßen oder um ungesetzliche, schädliche, verantwortungslose oder unangemessene Zwecke zu verfolgen oder um auf eine Weise gegen diese Vereinbarung zu verstoßen.<br />
                    <br />
                    <b>Benutzerbeiträge.</b><br />
                    Sie verstehen, dass Ihre Inhalte möglicherweise unverschlüsselt übertragen werden und Übertragungen über verschiedene Netzwerke sowie Änderungen beinhalten, um die technischen Anforderungen zum Verbinden von Netzwerken oder Geräten zu erfüllen und anzupassen.<br />
                    1. Verantwortung. Mit den Diensten können Sie und andere Benutzer Inhalte übermitteln, hosten, freigeben und veröffentlichen („Benutzerbeiträge“). Sie verstehen, dass unabhängig davon, ob solche Benutzerbeiträge veröffentlicht werden oder nicht, keine Vertraulichkeit in Bezug auf Benutzerbeiträge garantiert wird. Sie tragen die alleinige Verantwortung für Ihre Nutzerbeiträge und die Folgen ihrer Posten, Veröffentlichung oder ihres Uploads. Es liegt in unserem alleinigen Ermessen, Ihre Nutzerbeiträge zu veröffentlichen und wir behalten uns das Recht vor, nach eigenem Ermessen und ohne vorherige Ankündigung alle auf den Diensten veröffentlichten Inhalte zu überwachen, zu zensieren, zu bearbeiten, zu entfernen, zu löschen und/oder zu entfernen (einschließlich Nutzerbeiträge) zu jeder Zeit und aus jedem Grund.<br />
                    2. Eigentum. Sie versichern und garantieren, dass Sie die erforderlichen Rechte und Berechtigungen besitzen, um RichList zu autorisieren, alle Rechte an geistigem Eigentum  (nachstehend definierten) in und für Ihre Benutzerbeiträge zu verwenden und deren Aufnahme und Verwendung gemäß den Bestimmungen der Dienste und dieser Allgemeinen Geschäftsbedingungen. Sofern nicht gesondert auf die Nutzerbeiträge Bezug genommen wird, umfassen alle Verweise auf Inhalte in diesem Dokument auch Verweise auf Nutzerbeiträge. "Rechte an geistigem Eigentum" bezeichnet alle Rechte, Titel und Interessen, egal ob im In- oder Ausland, in und an allen Geschäftsgeheimnissen, Patente, Urheberrechte, Dienstleistungsmarken, Handelsmarken, Know-how oder ähnliche Rechte an geistigem Eigentum sowie alle moralischen Rechte, Rechte auf Privatsphäre, Werbung und ähnliche Rechte jeglicher Art gemäß den Gesetzen oder Vorschriften von Behörden, Aufsichtsbehörden, oder Justizbehörde, ausländische oder inländische. Sie behalten alle Ihre Eigentumsrechte an und für Ihre Benutzerbeiträge.<br />
                    3. Lizenz für Benutzerbeiträge. Indem Sie die Benutzerbeiträge an RichList senden, gewähren Sie RichList und seinen Partnern hiermit eine weltweite, unwiderrufliche, nicht exklusive, gebührenfreie, unbefristete, unterlizenzierbare und übertragbare Lizenz zur Nutzung, Bearbeitung, Archivierung, Übertragung, Ausstrahlung, zum Verkauf, Übersetzen, Veröffentlichen, Reproduzieren, Verteilen, Vorbereiten von abgeleiteten Werken, Anzeigen und Durchführen der Benutzerbeiträge, sowie Ihres Namens o.ä. und anderer identifizierender Informationen, die Teil eines Benutzerbeitrags sind, und deren Nutzung in Verbindung mit den Services und Geschäften von RichList, einschließlich, jedoch nicht beschränkt auf die Entwicklung, Herstellung und Vermarktung von Produkten, das Veröffentlichen und Weiterverbreiten eines Teils oder aller Ihrer Benutzerbeiträge (und abgeleiteter Werke davon) in jeglicher Form, Medien, Software oder Technologie jeglicher Art, die jetzt bekannt sind oder in Zukunft entwickelt werden, und Sie verzichten hiermit auf moralische Rechte an Ihren Benutzerbeiträgen, im gesetzlich zulässigen Umfang. Sie gewähren hiermit auch jedem Benutzer der Dienste oder anderen Benutzern der Benutzerbeiträgen ein nicht ausschließliches Recht, solche Benutzerbeiträge zu verwenden, zu reproduzieren, zu verteilen, abgeleitete Werke davon zu erstellen, anzuzeigen und auszuführen, dies alles in Übereinstimmung mit diesen Bedingungen.<br />
                    4. Verbotener Inhalt. Sie erklären sich damit einverstanden, dass Sie keine Benutzereingaben anzeigen, posten, veröffentlichen, hochladen oder übertragen, die: (i) nach den Verbraucherschutzgesetzen einer Gerichtsbarkeit unfair oder irreführend sind; (ii) urheberrechtlich geschützt, durch Geschäftsgeheimnisse geschützt oder anderweitig Eigentumsrechten Dritter unterliegen, einschließlich Datenschutz- und Publizitätsrechten, es sei denn, Sie sind Inhaber solcher Rechte. (iii) die Sicherheit oder Gesundheit einer Person gefährdet, die öffentliche Sicherheit oder Gesundheit gefährdet, die nationale Sicherheit gefährdet oder eine Untersuchung durch die Strafverfolgungsbehörden stört; (iv) sich als eine andere Person ausgeben; (v) illegaler Drogen fördern, gegen Exportkontrollgesetze verstoén, im Zusammenhang mit illegalem Glücksspiel oder illegalem Waffenhandel stehen; (vi) rechtswidrig, diffamierend, verleumderisch, bedrohlich, pornografisch, belästigend, hasserfüllt, rassistisch oder ethnisch anstößig sind oder Verhaltensweisen fördern, die als Straftat angesehen werden, zu zivilrechtlicher Haftung führen, gegen Gesetze verstoßen oder unangemessen sind; (vii) Diebstahl oder Terrorismus beinhalten; (viii) ein Foto oder Video einer anderen Person enthält, die Sie ohne deren Zustimmung eingestellt haben; (ix) die Datenschutzrechte, Publizitätsrechte, Rechte an geistigem Eigentum, Vertragsrechte oder sonstige Rechte einer Person verletzt oder versucht, diese zu verletzen; oder (x) anderweitig böswillig oder betrügerisch sind.<br />
                    5. Exposition. Sie verstehen und erkennen an, dass Sie beim Zugriff auf und bei der Nutzung der Dienste: (i) Benutzerbeiträgen aus verschiedenen Quellen ausgesetzt sind und dass RichList nicht für die Richtigkeit, Nützlichkeit, Sicherheit oder Rechte an geistigem Eigentum von oder in Bezug auf diese verantwortlich ist an solche Nutzerbeiträge; und (ii) Sie möglicherweise Benutzerbeiträgen ausgesetzt sind, die ungenau, anstößig, unanständig oder verwerflich sind. Sie erklären sich hiermit einverstanden, in Bezug auf (i) und (ii) hierin auf alle rechtlichen oder gerechten Rechte oder Rechtsmittel zu verzichten, die Sie möglicherweise gegen RichList haben.<br />
                    <br />
                    <b>Copyright.</b><br />
                    Wir halten uns an das Urheberrecht und reagieren auf Beschwerden über Urheberrechtsverletzungen. Wir respektieren das geistige Eigentum anderer und bitten Sie, dies auch zu tun. Wir reagieren auf Hinweise auf mutmaßliche Urheberrechtsverletzungen, wenn diese gesetzeskonform sind. Wir behalten uns das Recht vor, mutmaßlich rechtsverletzende Inhalte zu löschen oder zu deaktivieren und Accounts von wiederholten Rechtsverletzern ohne Erstattung zu entfernen. Bei Beschwerden kontaktieren Sie uns bitte unter richlistapp(at)gmail.com.<br />
                    <br />
                    <b>Links.</b><br />
                    Die Dienste enthalten möglicherweise Links und ermöglichen Ihnen das Posten von Inhalten auf Websites von Drittanbietern, die nicht Eigentum von RichList sind oder von RichList kontrolliert werden. Wir sind nicht mit Websites Dritter verbunden, haben keine Kontrolle über diese und übernehmen keine Verantwortung für deren Inhalt, Datenschutzrichtlinien oder Praktiken. Sie: (i) sind allein verantwortlich und haftbar für Ihre Nutzung und Verlinkung von Websites Dritter sowie für jegliche Inhalte, die Sie an Websites Dritter senden oder auf Websites Dritter posten; und (ii) entbinden Sie RichList ausdrücklich von jeglicher Haftung, die sich aus Ihrer Nutzung von Websites Dritter ergibt. Aus diesem Grund empfehlen wir Ihnen, die Allgemeinen Geschäftsbedingungen und Datenschutzbestimmungen aller Websites Dritter zu lesen, die Sie möglicherweise besuchen.<br />
                    <br />
                    Mit RichList können Sie auf eine Seite verlinken, sofern: (i) Sie auf eine Seite verlinken, diese aber nicht replizieren; (ii) der Hyperlink-Text muss den Inhalt der Website beschreiben. (iii) Sie die Beziehung zu RichList nicht falsch darstellen oder falsche Informationen über RichList angeben und nicht impliziert wird, dass wir Dienstleistungen oder Produkte unterstützen, es sei denn, wir haben Ihnen zuvor unsere ausdrückliche Zustimmung erteilt. (iv) Sie dürfen keine Links von einer Website verwenden, die das Verlinken mit Drittanbietern untersagen. (v) diese Website Dritter enthält keine Inhalte, die (a) beleidigend oder kontrovers sind (beides nach unserem Ermessen) oder (b) geistiges Eigentum, Datenschutzrechte oder andere Rechte einer Person oder Organisation verletzen; und/oder (vi) Sie und die Website mit diesen Bedingungen und geltendem Recht übereinstimmen.<br />
                    <br />
                    <b>Datenschutz.</b><br />
                    Wir verwenden alle persönlichen Informationen, die wir im Zusammenhang mit den Diensten sammeln oder erhalten, gemäß unserer Datenschutzrichtlinie, die unter www.richlist.net/datenschutz.html verfügbar ist. Sie stimmen zu, dass wir personenbezogene Daten verwenden dürfen, die Sie uns gemäß den Datenschutzbestimmungen zur Verfügung stellen oder angeben.<br />
                    <br />
                    <b>Gewährleistungsausschluss.</b><br />
                    1. Dieser Abschnitt gilt unabhängig davon, ob die im Rahmen der Dienste erbrachten Dienstleistungen für Zahlungen sind oder nicht. Das anwendbare Recht erlaubt möglicherweise nicht den Ausschluss bestimmter Garantien, weshalb bestimmte hierin dargelegte Ausschlüsse möglicherweise nicht zutreffen.<br />
                    2. DIE DIENSTLEISTUNGEN WERDEN "WIE SIE SIND" UND "WIE VERFÜGBAR" UND OHNE JEGLICHE AUSDRÜCKLICHE ODER STILLSCHWEIGENDE GEWÄHRLEISTUNGEN BEREITGESTELLT. RICHLIST LEHNT HIERMIT ALLE AUSDRÜCKLICHEN ODER STILLSCHWEIGENDEN GEWÄHRLEISTUNGEN AB, EINSCHLIESSLICH, ABER NICHT BESCHRÄNKT AUF STILLSCHWEIGENDE GEWÄHRLEISTUNGEN DER MARKTGÄNGIGKEIT, DES EIGENTUMS, DER EIGNUNG FÜR EINEN BESTIMMTEN ZWECK, DER NICHTVERLETZUNG UND DERJENIGEN, DIE SICH AUS DEM GESETZ ODER AUS EINEM HANDELSVERKEHR ODER DER NUTZUNG DES HANDELS ERGEBEN. RICHLIST GARANTIERT NICHT, DASS DIE DIENSTE FREI VON BUGS, SICHERHEITSVERLETZUNGEN ODER VIRENANGRIFFEN SIND. DIE DIENSTE KÖNNEN GELEGENTLICH AUS ROUTINEMÄßIGEN WARTUNGS-, UPGRADE- ODER ANDEREN GRÜNDEN NICHT VERFÜGBAR SEIN. SIE STIMMEN ZU, DASS RICHLIST NICHT FÜR FOLGEN VERANTWORTLICH IST, DIE IHNEN ODER DRITTEN DURCH TECHNISCHE PROBLEME IM INTERNET, LANGSAME VERBINDUNGEN, VERKEHRSSTÖRUNGEN ODER ÜBERLASTUNG UNSERER ODER ANDERER SERVER ENTSTEHEN KÖNNEN.  WIR GARANTIEREN, UNTERSTÜTZEN ODER GARANTIEREN KEINE INHALTE, PRODUKTE ODER DIENSTLEISTUNGEN, DIE AUF DEN DIENSTEN VON DRITTPARTEIEN ANGEBOTEN ODER BEWORBEN WERDEN..<br />
                    3. RICHLIST ÜBERNIMMT KEINE GEWÄHRLEISTUNG, BILLIGUNG ODER GARANTIE FÜR IN EINER BENUTZERBEITRAG ENTHALTENE INHALTE UND ÜBERNIMMT KEINE ZUSICHERUNG ODER GARANTIE IN BEZUG AUF DIESE INHALTE UND LEHNT JEGLICHE HAFTUNG FÜR DIESE AB.<br />
                    4. SIE ERKENNEN AUSDRÜCKLICH AN, DASS RICHLIST NICHT FÜR DIE EINGABEN ODER DAS VERHALTEN (EINSCHLIESSLICH DIFFAMIERENDEN, BELEIDIGENDEN, ILLEGALEN ODER FAHRLÄSSIGEN VERHALTENS) EINES DIENSTBENUTZERS VERANTWORTLICH IST UND DASS DAS RISIKO VON SCHÄDEN ODER SCHÄDEN AUS DEM VORSTEHENDEN VOLLSTÄNDIG BEI IHNEN LIEGT.<br />
                    5. IHR VERTRAUEN AUF ODER IHRE NUTZUNG VON BENUTZERBEITRÄGEN ODER INTERAKTIONEN MIT DIENSTEN, NUTZERN ODER EIGENTÜMERN, GESCHIEHT AUF IHR EIGENES RISIKO. WENN SIE EINEN STREIT MIT EINEM DIENSTBENUTZER ODER EIGENTÜMER IM ZUSAMMENHANG MIT DEN DIENSTEN ODER EINER BENUTZERBEITRAG HABEN, STIMMEN SIE ZU, DASS RICHLIST NICHT FÜR ANSPRÜCHE ODER SCHÄDEN HAFTBAR GEMACHT WERDEN KANN, DIE SICH AUS ODER IM ZUSAMMENHANG MIT EINEM SOLCHEN STREIT ERGEBEN. RICHLIST BEHÄLT SICH DAS RECHT VOR, IST ABER NICHT VERPFLICHTET, SOLCHE STREITIGKEITEN ZU ÜBERWACHEN.<br />
                    6.MIT AUSNAHME DER IN UNSERER DATENSCHUTZERKLÄRUNG AUSDRÜCKLICH GENANNTEN ZUSICHERUNGEN, GARANTIEN ODER BEDINGUNGEN JEGLICHER ART, WEDER AUSDRÜCKLICH NOCH STILLSCHWEIGEND, HINSICHTLICH DER SICHERHEIT VON INFORMATIONEN, DIE SIE ZUR VERFÜGUNG STELLEN, ODER VON AKTIVITÄTEN, DIE SIE WÄHREND DER NUTZUNG DER DIENSTE AUSÜBEN.<br />
                    <br />
                    <b>Haftungsbeschränkung.</b><br />
                    SOWEIT GESETZLICH ZULÄSSIG, HAFTET RICHLIST NICHT FÜR DIREKTE, INDIREKTE, EXEMPLARISCHE, BESONDERE, FOLGE- ODER ZUFÄLLIGE SCHÄDEN JEGLICHER ART ODER FÜR DATEN-, UMSATZ-, GEWINN- ODER REPUTATIONSVERLUSTE, DIE SICH AUS DIESEN BEDINGUNGEN ODER AUS IHRER NUTZUNG ODER UNMÖGLICHKEIT DER NUTZUNG DER DIENSTE ERGEBEN, SELBST WENN RICHLIST ÜBER DIE MÖGLICHKEIT SOLCHER SCHÄDEN ODER VERLUSTE INFORMIERT WURDE. Einige Gerichtsbarkeiten erlauben keine Beschränkung oder keinen Ausschluss der Haftung für Neben- oder Folgeschäden, in diesen Gerichtsbarkeiten ist unsere Haftung auf das gesetzlich maximal zulässige Maß beschränkt.<br />
                    <br />
                    <b>Entschädigung.</b><br />
                    Sie erklären sich damit einverstanden, RichList und unsere verbundenen Unternehmen sowie unsere jeweiligen Führungskräfte, Direktoren, Mitarbeiter und Vertreter vor und gegen alle Ansprüche, Schäden, Verpflichtungen, Verluste, Verbindlichkeiten, Kosten und Ausgaben (einschließlich, aber nicht beschränkt auf Anwaltsgebühren) zu verteidigen, freizustellen und schadlos zu halten, die sich aus folgenden Gründen ergeben: (i) Ihrer Nutzung oder Unmöglichkeit der Nutzung der Dienste; (ii) Ihren Benutzerbeiträgen; (iii) Ihrer Interaktion mit einem Benutzer; oder (iv) Ihrer Verletzung dieser Bedingungen.<br />
                    <br />
                    <b>Updates und Upgrades.</b><br />
                    Wir können von Zeit zu Zeit Aktualisierungen oder Upgrades der App oder der Website (jeweils eine "Revision") bereitstellen, sind aber nicht dazu verpflichtet. Solche Überarbeitungen werden gemäß unseren jeweils aktuellen Richtlinien geliefert, die eine automatische Aktualisierung oder Aktualisierung ohne zusätzliche Mitteilung an Sie beinhalten können. Sie stimmen einer solchen automatischen Aktualisierung oder Aktualisierung der App oder der Website zu. Alle hierin enthaltenen Verweise auf die App und die Website müssen Änderungen enthalten. Diese Vereinbarung gilt für alle Änderungen, die die ursprüngliche App oder Website ersetzen oder ergänzen, es sei denn, die Revision wird von einer separaten Lizenzvereinbarung begleitet, die die Revision regelt.<br />
                    <br />
                    <b>Open Source-Software von Drittanbietern.</b><br />
                    Teile der Dienste können Drittanbieter- oder Open-Source-Software beinhalten, die den Bedingungen Dritter unterliegt ("Drittanbieter-Bedingungen"). Solche dritter Parteien spezifischen Lizenzbedingungen und das dazugehörige Copyright. Wir sind nicht verantwortlich für eine solche Software. Im Falle eines Widerspruchs zwischen den Bedingungen eines Dritten und den Bedingungen dieser Bedingungen haben die Bedingungen des Dritten Vorrang, jedoch ausschließlich in Verbindung mit der zugehörigen Open-Source-Software des Dritten.<br />
                    <br />
                    <b>Laufzeit und Kündigung.</b><br />
                    Diese Bedingungen gelten bis zur Kündigung durch RichList oder Sie. RichList hat nach eigenem Ermessen das Recht, diese Bedingungen und/oder Ihren Zugang zu den Diensten oder Teilen davon jederzeit und mit oder ohne Grund (einschließlich, aber nicht beschränkt auf einen Verstoß gegen diese Bedingungen) sofort zu kündigen. RichList haftet weder Ihnen noch einem Dritten gegenüber für die Beendigung der Dienste oder eines Teils davon. Wenn Sie einer Bestimmung oder Bedingung dieser Bedingungen oder nachfolgenden Änderungen widersprechen oder in irgendeiner Weise mit den Diensten unzufrieden sind, besteht Ihre einzige Möglichkeit darin, die Nutzung der Dienste unverzüglich einzustellen. Nach Beendigung dieser Bedingungen sind Sie verpflichtet, die Nutzung der Dienste einzustellen. Dieser Abschnitt und die Abschnitte "Rechte an geistigem Eigentum", "Lizenz für Benutzerbeiträge", "Datenschutz", "Gewährleistungsausschluss", "Haftungsbeschränkung", "Entschädigung" und "Unabhängige Auftragnehmer" bis "Allgemeines" gelten auch nach Beendigung dieser Bedingungen.<br />
                    <br />
                    <b>Unabhängige Auftragnehmer.</b><br />
                    Sie und RichList sind unabhängige Auftragnehmer. Nichts in diesen Bedingungen begründet eine Partnerschaft, ein Joint Venture, eine Agentur oder ein Arbeitsverhältnis zwischen Ihnen und RichList. Sie dürfen unter keinen Umständen Garantien, Gewährleistungen, Zusicherungen, Verpflichtungen oder Verpflichtungen im Namen von RichList abgeben oder übernehmen.<br />
                    <br />
                    <b>Zuordnung.</b><br />
                    Diese Bedingungen sowie alle hierin gewährten Rechte und Lizenzen dürfen nicht von Ihnen übertragen oder abgetreten werden, sondern können von RichList ohne Einschränkung oder Benachrichtigung an Sie abgetreten werden. Jede verbotene Abtretung ist null und nichtig.<br />
                    <br />
                    <b>Geltendes Recht.</b><br />
                    RichList behält sich das Recht vor, jeden Aspekt der Dienste jederzeit einzustellen oder zu ändern. Diese Bedingungen und die Beziehung zwischen Ihnen und RichList unterliegen dem Recht des Landes Deutschland, ohne Rücksicht auf dessen Grundsätze des Kollisionsrechts.<br />
                    <br />
                    <b>Allgemeines. </b><br />
                    Diese Bedingungen bilden die gesamte Vereinbarung zwischen Ihnen und RichList bezüglich der Dienste. Wenn eine Bestimmung dieser Bedingungen von einem zuständigen Gericht für ungültig erklärt wird, berührt die Ungültigkeit dieser Bestimmung nicht die Gültigkeit der übrigen Bestimmungen dieser Bedingungen, die in vollem Umfang in Kraft und Wirkung bleiben. Kein Verzicht auf eine Bestimmung dieser Bedingungen gilt als weiterer oder anhaltender Verzicht auf diese Bestimmung oder eine andere Bestimmung, und das Versäumnis einer Partei, ein Recht oder eine Bestimmung unter diesen Bedingungen geltend zu machen, stellt keinen Verzicht auf dieses Recht oder diese Bestimmung dar. <br />
                    </p>
            </div>
        </div>
        );
    }
}
