import React from 'react';

export default class Datenschutz extends React.Component {
    render() {
        return (
            <div className="container">
                <div className="termctn">
                    <p className="terms language"><a className="linkcolor" href="privacy">For the English privacy notices click here.</a> </p>
                    <p className="header">Datenschutzerklärung der Richlist-Webseite</p>
                    
                    <p className="terms"><br />
                        Diese Datenschutz-Erklärung dient der Information darüber, welche Art von Daten von RICHLIST auf www.RICHLIST.net erhoben, gespeichert und verarbeitet werden und wie RICHLIST den Schutz und die Sicherheit der personenbezogenen Daten gewährleistet.
                        <br /><br />1. Grundsätzliche Information
                        <br />Soweit in den folgenden Abschnitten nicht anderweitig dargestellt, werden bei Nutzung unserer Webseiten grundsätzlich keine personenbezogenen Daten erhoben, verarbeitet oder genutzt.
                        <br />Wenn Sie auf unsere Internetseiten zugreifen, erfassen unsere Web-Server automatisch Informationen allgemeiner Natur. Dazu gehören die Art des Webbrowsers, das verwendete Betriebssystem, der Domainname des Internet Service Providers, die IP-Adresse des verwendeten Computers, die Webseite, von der aus Sie uns besuchen, die Seiten, die Sie bei uns besuchen sowie das Datum und die Dauer des Besuches.
                        <br />Diese Daten können von uns nicht dazu verwendet werden, den einzelnen Nutzer zu identifizieren. Die Informationen werden von uns lediglich statistisch ausgewertet und ausschließlich dazu verwendet, die Attraktivität, Inhalte und Funktionalitäten unserer Webseiten zu verbessern.
                        <br /><br />2. Personenbezogene Daten
                        <br />In der EU-Datenschutz-Grundverordnung (DSGVO), sind personenbezogene Daten folgendermaßen definiert:
                        <br />Alle Informationen, die sich auf eine identifizierte oder identifizierbare natürliche Person (im Folgenden „betroffene Person“) beziehen; als identifizierbar wird eine natürliche Person angesehen, die direkt oder indirekt, insbesondere mittels Zuordnung zu einer Kennung wie einem Namen, zu einer Kennnummer, zu Standortdaten, zu einer Online-Kennung oder zu einem oder mehreren besonderen Merkmalen identifiziert werden kann, die Ausdruck der physischen, physiologischen, genetischen, psychischen, wirtschaftlichen, kulturellen oder sozialen Identität dieser natürlichen Person sind.
                        <br /><br />3. Rechtsgrundlage für die Erhebung Verarbeitung personenbezogener Daten
                        <br />Soweit wir für Verarbeitungsvorgänge personenbezogener Daten Ihre Einwilligung einholen, dient Art. 6 Abs. 1 lit. a DSGVO als Rechtsgrundlage für die Verarbeitung Ihrer personenbezogener Daten.
                        <br />Bei der Verarbeitung Ihrer personenbezogenen Daten zur Erfüllung eines Vertrages zwischen Ihnen und RICHLIST, dient Art. 6 Abs. 1 lit. b DSGVO als Rechtsgrundlage. Dies gilt auch für Verarbeitungsvorgänge, die zur Durchführung vorvertraglicher Maßnahmen erforderlich sind.
                        <br />Soweit eine Verarbeitung personenbezogener Daten zur Erfüllung einer rechtlichen Verpflichtung erforderlich ist, der unser Unternehmen unterliegt, dient Art. 6 Abs. 1 lit. c DSGVO als Rechtsgrundlage.
                        <br />Ist die Verarbeitung zur Wahrung eines berechtigten Interesses unseres Unternehmens oder eines Dritten erforderlich und überwiegen die Interessen, Grundrechte und Grundfreiheiten des Betroffenen das erstgenannte Interesse nicht, so dient Art. 6 Abs. 1 lit. f DSGVO als Rechtsgrundlage für die Verarbeitung.
                        <br /><br />4. Datenlöschung und Speicherdauer
                        <br />Die personenbezogenen Daten der betroffenen Person werden gelöscht oder gesperrt, sobald der Zweck der Speicherung entfällt. Eine Speicherung kann darüber hinaus dann erfolgen, wenn dies durch den europäischen oder nationalen Gesetzgeber in unionsrechtlichen Verordnungen, Gesetzen oder sonstigen Vorschriften, denen der Verantwortliche unterliegt, vorgesehen wurde. Eine Sperrung oder Löschung der Daten erfolgt auch dann, wenn eine durch die genannten Normen vorgeschriebene Speicherfrist abläuft, es sei denn, dass eine Erforderlichkeit zur weiteren Speicherung der Daten für einen Vertragsabschluss oder eine Vertragserfüllung besteht.
                        <br /><br />5. Erhebung und Verarbeitung personenbezogener Daten
                        <br />Personenbezogene Daten werden von uns nur erfasst, wenn Sie uns diese von sich aus mitteilen, beispielsweise wenn Sie sich bei uns registrieren oder mit uns in Kontakt treten.
                        <br />Wir verwenden die von Ihnen angegebenen personenbezogenen Daten ausschließlich, soweit Ihre Daten zur Erfüllung unserer Dienstleistungen notwendig sind.
                        <br />Eine darüber hinaus gehende Verwendung Ihrer Daten, beispielsweise zu weiteren Serviceleistungen oder Werbezwecken, findet nur statt, wenn Sie zuvor ausdrücklich dazu eingewilligt haben. Ihre Einwilligung können Sie jederzeit für die Zukunft widerrufen.
                        <br />Nach vollständiger Vertragsabwicklung werden Ihre Daten für die weitere Verwendung gesperrt, es sei denn, Sie haben gesondert in die weitere Verwendung eingewilligt. Nach Ablauf der steuer- und handelsrechtlichen Fristen werden diese Daten gelöscht, sofern Sie nicht ausdrücklich in eine weitere Nutzung eingewilligt haben.
                        <br />Nachstehende Regelungen informieren Sie insoweit über die Art, den Umfang und Zweck der Erhebung, die Nutzung und die Verarbeitung von personenbezogenen Daten.
                        <br /><br />6. Kontakt
                        <br />Sie haben die Möglichkeit uns bei Fragen, Wünschen und Anregungen zu kontaktieren. Dies können Sie u.a. per E-Mail tun. Soweit wir über unser Kontaktformular Eingaben abfragen, sind dies nur die zur Bearbeitung der Anfrage zwingend notwendigen Angaben. Diese Angaben dienen uns zur Konkretisierung Ihrer Anfrage und zur verbesserten Abwicklung Ihres Anliegens. In diesem Fall werden die von Ihnen gemachten Angaben zum Zwecke der Bearbeitung Ihrer Kontaktaufnahme gespeichert. Darüber hinaus erfolgt ein Abgleich der so erhobenen Daten mit Daten, die möglicherweise anderweitig von uns erhoben werden, wenn Sie uns vorher eine entsprechende Einwilligung erteilt haben, die Sie jederzeit mit Wirkung für die Zukunft widerrufen können. Für die Ausübung des Widerrufs wenden Sie sich bitte an die am Ende dieser Erklärung genannte Stelle.
                        <br /> 
                        <br />7. Datenübermittlung an Dritte
                        <br />Ihre Daten werden Dienstleistungspartner weitergegeben, sofern diese in unserem Auftrag tätig sind und RICHLIST bei der Erbringung ihrer Dienste unterstützen.
                        <br />Eine Verarbeitung Ihrer personenbezogenen Daten durch beauftragte Dienstleister erfolgt im Rahmen der Auftragsverarbeitung gem. Art. 28 DSGVO.
                        <br />Die zuvor genannten Dienstleister erhalten lediglich Zugang zu solchen persönlichen Informationen, die zur Erfüllung der jeweiligen Tätigkeit erforderlich sind. Es ist diesen Dienstleistern untersagt, Ihre persönlichen Informationen weiterzugeben oder zu anderen Zwecken zu verwenden, insbesondere zu eigenen werblichen Zwecken.
                        <br />Soweit externe Dienstleister mit Ihren personenbezogenen Daten in Berührung kommen, haben wir durch rechtliche, technische und organisatorische Maßnahmen sowie durch regelmäßige Kontrollen sichergestellt, dass auch diese die geltenden Datenschutzvorschriften einhalten.
                        <br />Eine kommerzielle Weitergabe Ihrer personenbezogenen Daten an andere Unternehmen erfolgt nicht.
                        <br /><br />8. Google Analytics
                        <br />Diese Webseite verwendet Google Analytics der Firma Google Ireland Limited (Gordon House, Barrow Street, Dublin 4, Irland). Gemäß der Vereinbarung zwischen Google und dem Hamburgischen Beauftragten für Datenschutz und Informationsfreiheit ist eine datenschutzkonforme und beanstandungsfreie Nutzung von Google Analytics unter bestimmten Bedingungen möglich. Insbesondere weisen wir darauf hin, dass auf dieser Webseite Google Analytics um die IP-Masking Funktion „_gat._anonymizeIp“ erweitert wurde, um eine anonymisierte Erfassung von IP-Adressen zu gewährleisten.
                        <br />Bitte beachten Sie auch die nachfolgenden Informationen zum Einsatz von Google Analytics:
                        <br />Google Analytics verwendet Cookies, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Webseite durch Sie ermöglichen. Die durch das Cookie erzeugten Informationen über Ihre Benutzung dieser Webseite werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert. Durch Aktivierung der IP-Anonymisierung auf dieser Webseite, wird Ihre IP-Adresse von Google jedoch innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum zuvor gekürzt. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. Im Auftrag des Betreibers dieser Webseite wird Google diese Informationen benutzen, um Ihre Nutzung der Webseite auszuwerten, um Reports über die Webseitenaktivitäten zusammenzustellen und um weitere mit der Webseitennutzung und der Internetnutzung verbundene Dienstleistungen gegenüber dem Webseitenbetreiber zu erbringen.
                        <br />Die im Rahmen von Google Analytics von Ihrem Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt. Sie können die Speicherung der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Webseite vollumfänglich werden nutzen können. Sie können darüber hinaus die Erfassung der durch das Cookie erzeugten und auf Ihre Nutzung der Webseite bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem Sie das unter dem folgenden Link verfügbare Browser-Plugin herunterladen und installieren.
                        <br />Sie können alternativ die Erfassung durch Google Analytics auch verhindern, indem Sie auf folgenden Link klicken. Es wird ein Opt-Out-Cookie gesetzt, das die zukünftige Erfassung Ihrer Daten beim Besuch dieser Website verhindert: Google Analytics deaktivieren. Das Opt-Out-Cookie gilt nur für diesen Browser und auch nur für diese Domain. Löschen Sie Ihre Cookies in diesem Browser, müssen Sie diesen Link erneut klicken.
                        <br />Nähere Informationen hierzu finden Sie unter https://www.google.de/intl/de/policies/ sowie in der Datenschutzerklärung von Google.
                        <br /><br />9. Soziale Netzwerke
                        <br />Auf unserer Webseite sind Social Plugins der sozialen Netzwerke Facebook, Twitter und Instagram integriert. Die Plugins sind auf unserer Webseite mittels Symbol des jeweiligen Netzwerks und dem Namen, lediglich als Link zu dem entsprechenden Dienst eingebunden. Nach dem Anklicken der eingebundenen Grafik werden Sie auf die Seite des Anbieters weitergeleitet, d.h. erst dann werden ggf. Nutzerinformationen an den Anbieter übertragen. Wenn Sie auf den Link eines Dienstes unter der Textzeile „Folgen Sie uns“ klicken, können Sie unsere Aktivitäten auf der jeweiligen Plattform verfolgen. RICHLIST hat keinen Einfluss auf die Erhebung, Verarbeitung und Nutzung von Daten der jeweiligen Netzwerke. Informationen zum Umgang mit Ihren personenbezogenen Daten bei Nutzung dieser Webseiten entnehmen Sie bitte den Datenschutzbestimmungen der jeweiligen Netzwerke.
                        <br /><br />10. Datensicherheit
                        <br />RICHLIST setzt technische und organisatorische Sicherheitsmaßnahmen ein, um Ihre durch uns verwalteten Daten gegen zufällige oder vorsätzliche Manipulationen, Verlust, Zerstörung oder vor dem Zugriff unberechtigter Personen zu schützen. Unsere Sicherheitsmaßnahmen werden entsprechend der technologischen Entwicklung fortlaufend verbessert.
                        <br />Werden personenbezogene Daten von Ihnen verarbeitet, sind Sie Betroffener i.S.d. DSGVO und es stehen Ihnen folgende Rechte gegenüber dem Verantwortlichen zu:
                        <br />Auskunftsrecht nach Artikel 15 DSGVO
                        <br />Sie können von uns eine Bestätigung darüber verlangen, ob personenbezogene Daten, die Sie betreffen, von uns verarbeitet werden. Wenn wir Daten von Ihnen verarbeitet haben stehen Ihnen weitere in Artikel 15 DSGVO genannte Auskunftsrechte zu.
                        <br />Recht auf Berichtigung
                        <br />Sind Ihre Daten, die wir von Ihnen erfasst haben unrichtig oder unvollständig, können Sie von uns unverzüglich Berichtigung nach Artikel 16 DSGVO verlangen.
                        <br />Recht auf Einschränkung der Verarbeitung
                        <br />Unter den Voraussetzungen des Artikels 18 DSGVO können Sie zudem unter Umständen auch die Einschränkung der Verarbeitung der Sie betreffenden personenbezogenen Daten verlangen.
                        <br />Nach der Einschränkung dürfen Ihre Daten nur mit Ihrer Einwilligung oder zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen, oder zum Schutz der Rechte einer anderen natürlichen oder juristischen Person, oder aus Gründen eines wichtigen öffentlichen Interesses der Union oder eines Mitgliedstaats verarbeitet werden. Wir unterrichten Sie bevor die Einschränkung aufgehoben wird.
                        <br />Recht auf Löschung
                        <br />Sie können bei Vorliegen von einem der Gründe aus Artikel 17 Abs. 1 DSGVO von uns die unverzügliche Löschung der Sie betreffenden personenbezogenen Daten verlangen, es sei denn es besteht eine Ausnahme von der Löschpflicht nach Artikel 17 Abs. 3 DSGVO.
                        <br />Recht auf Unterrichtung
                        <br />Haben Sie das Recht auf Berichtigung, Löschung oder Einschränkung der Verarbeitung gegenüber uns geltend gemacht, sind wir gemäß Artikel 19 DSGVO verpflichtet allen Empfängern Ihrer personenbezogenen Daten dies mitzuteilen, außer die Mitteilung ist unmöglich oder mit unverhältnismäßigen Aufwand verbunden. Sie haben zudem das Recht über die Empfänger unterrichtet zu werden. Ihnen steht gegenüber dem Verantwortlichen das Recht zu, über diese Empfänger unterrichtet zu werden.
                        <br />Recht auf Datenübertragbarkeit
                        <br />Außerdem haben Sie nach Artikel 20 DSGVO das Recht, von uns die Sie betreffenden personenbezogenen Daten, in maschinenlesbaren Format zu erhalten und die Daten einem anderen Verantwortlichen ohne Behinderung zu übermitteln, sofern die Voraussetzungen des Artikel 20 Abs. 1 lit.a DSGVO vorliegen, oder zu erwirken, dass Ihre personenbezogenen Daten direkt von uns einem anderen Verantwortlichen übermittelt werden, soweit dies technisch machbar ist und keine Freiheiten und Rechte anderer Personen dadurch beeinträchtigt werden. Dieses Recht gilt nicht für eine Verarbeitung personenbezogener Daten, die zur Wahrnehmung einer Aufgabe im öffentlichen Interesse, oder zur Ausübung öffentlicher Gewalt erforderlich ist.
                        <br /><br />11. Notwendige Angaben bei der Bezahlung 
                        <br />11.1 Bei der Bezahlung machen die Nutzer folgende Angaben:
                        <br />– Benutzername (Pseudonym)
                        <br />- Bildupload
                        <br />11.2 Wenn Sie In-App-Käufe über RICHLIST tätigen, geschieht dies über externe Zahlungsanbieter. Wir erheben und verarbeiten dabei keine Zahlungsdaten. Die Eingabe sowie Verarbeitung der Zahlungsdaten erfolgt direkt bei den Zahlungsanbietern. Zwischen uns und den Zahlungsanbietern werden lediglich technische Daten (u.a. die Transaktion ID) zur Validierung der Käufe ausgetauscht.
                        <br />11.3 Dritte können von den zwingend bei der Bezahlung angegebenen Daten nur folgende Angaben im “Profil” des Nutzers sehen:
                        <br />– Benutzername
                        <br />– Instagram-, Twitter-, Tiktok- und Snapchat-Accountname
                        <br />– Persönliche Nachricht
                        <br />– Bezahlter Betrag
                        <br />Alle weiteren Pflichtangaben (E-Mail-Adresse) sind für Dritte nicht einsehbar.
                        <br /> <br />12. Freiwillige Angaben
                        <br />12.1 Neben den Pflichtangaben kann jedes registrierte Mitglied in seinem Profil nach freiem Ermessen zahlreiche freiwillige Angaben zu seiner Person machen und ein oder mehrere Profilbilder einstellen. Diese freiwilligen Angaben sind zur Nutzung von RICHLIST zwar nicht erforderlich, erhöhen aber die Attraktivität des eigenen Profils und damit die Chance, mit anderen Mitgliedern in Kontakt zu kommen. Jedes Mitglied entscheidet frei darüber, welche zusätzlichen persönlichen Daten es über sich preisgeben und anderen Nutzern zugänglich machen möchte. Zu den freiwilligen Angaben, die das Mitglied ins Profil einstellen kann, zählen z. B.:
                        <br />– Twittername
                        <br />– Instagramname
                        <br />– Nachrichtentext
                        <br />– Persönliche Nachricht
                        <br />– Snapchatname
                        <br />– Tiktokname
                        <br /><br />13. Cookies und Tracking-Technologien
                        <br />Unsere Dienste und einige unserer Dienstleister verwenden "Cookies", anonyme Identifier und andere Tracking-Technologien, die uns helfen, unsere Dienste bereitzustellen und zu verbessern, Ihre Erfahrungen zu personalisieren und die Leistung unserer Aktivitäten und Kampagnen sowie die Nutzung unserer Apps, Spiele und Dienste insgesamt zu überwachen. Ein "Cookie" ist eine kleine Textdatei, die beispielsweise verwendet wird, um Daten über Aktivitäten auf unserer Website zu erheben. Einige Cookies und andere Technologien dienen dazu, personenbezogene Daten, wie z.B. eine IP-Adresse, die zuvor vom Nutzer übertragen wurde, abzurufen. So können wir beispielsweise Cookies verwenden, um Ihre Spracheinstellungen oder andere Einstellungen zu speichern, damit Sie diese nicht bei jeder Nutzung unserer Dienste neu einrichten müssen. Einige der von uns verwendeten Cookies sind mit Ihrem Konto verknüpft (einschließlich persönlicher Informationen über Sie, wie z.B. die E-Mail-Adresse, die Sie uns gegeben haben), andere Cookies nicht.
                        <br />Wir verwenden die folgenden Cookies:
                        <br />- Funktionale Cookies. Diese werden verwendet, um Sie zu erkennen, wenn Sie auf unsere Website zurückkehren. Dies ist für das Bezahlverfahren notwendig.
                        <br /> Obwohl wir unsere Maßnahmen nicht als Reaktion auf ein "Do-Not-Track"-Signal im HTTP-Header eines Browser oder einer mobilen Anwendung ändern, erlauben die meisten Browser es Ihnen, Cookies zu kontrollieren, einschließlich der Einstellungsmöglichkeit, ob Sie die Cookies akzeptieren möchten oder diese löschen möchten. Sie können die meisten Browser so einstellen, dass sie Sie benachrichtigen, wenn Sie ein Cookie erhalten, oder Sie können Cookies mit Ihrem Browser blockieren. Wir können jedoch nicht garantieren, dass unsere Dienste vollständig funktionieren, wenn Sie sich dafür entscheiden, Cookies zu blockieren. Beispielsweise werden alle Einstellungen, die Sie auf unserer Website oder in unserer App getätigt haben, dann nicht gespeichert.
                        <br /><br />14. Widerspruchsrecht
                        <br />Sie haben das Recht jederzeit gegenüber RICHLIST Widerspruch gegen die Verarbeitung der Sie betreffenden personenbezogenen Daten nach Art. 6 Abs. 1 lit.  f DSGVO einzulegen.
                        <br />Wir verarbeitet Ihre personenbezogenen Daten nicht mehr, es sei denn, schutzwürdige Gründe für die Verarbeitung überwiegen Ihre Interessen, Rechte und Freiheiten, oder die Verarbeitung dient der Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen.
                        <br />Recht auf Widerruf der datenschutzrechtlichen Einwilligungserklärung
                        <br />Sie haben jederzeit das Recht, Ihre datenschutzrechtliche Einwilligungserklärung mit Erklärung gegenüber RICHLIST zu widerrufen. Durch den Widerruf der Einwilligung wird die Rechtmäßigkeit der aufgrund der Einwilligung bis zum Widerruf erfolgten Verarbeitung nicht berührt.
                        <br />Recht auf Beschwerde bei der Aufsichtsbehörde
                        <br />Sie haben jederzeit unbeschadet eines anderweitigen verwaltungsrechtlichen oder gerichtlichen Rechtsbehelfs das Recht auf Beschwerde bei einer Aufsichtsbehörde, insbesondere in dem Mitgliedstaat ihres Aufenthaltsorts, ihres Arbeitsplatzes oder des Orts des mutmaßlichen Verstoßes, wenn Sie der Ansicht sind, dass die Verarbeitung der sie betreffenden personenbezogenen Daten gegen diese Verordnung verstößt.
                        <br />Änderungen der Datenschutzerklärung
                        <br />Diese aufgestellte Datenschutzerklärung wird laufend im Zuge der Weiterentwicklung des Internets oder unseres Angebots angepasst. Änderungen werden wir auf dieser Seite rechtzeitig bekanntgeben. Um sich hinsichtlich des aktuellen Stands unserer Datennutzungsbestimmungen zu informieren, sollte diese Seite regelmäßig aufgerufen werden.
                        <br /><br />15. Hosting und Backend-Struktur
                        <br />Firebase Cloud Functions, Firebase Cloud Storage und Firebase Realtime Database Personenbezogene Daten: Nutzungsdaten; verschiedene Datenarten, wie in der Datenschutzerklärung des Dienstes beschrieben
                        <br />Weitere Informationen  zu Firebase finden Sie hier: http://firebase.google.com
                        <br /><br />16. Datenschutzbeauftragte
                        <br />Wir stehen Ihnen auch im Falle von Auskunftsersuchen, Anträgen oder Beschwerden zur Verfügung:
                        <br />E-Mail: info(at)richlist.net
                        <br /><br />17. Google Vision AI
                        <br />Diese Seite nutzt über eine API den Bilderkennungsdienst Google Vision AI. Anbieter ist die Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA.
                        <br />Zur Nutzung der Funktionen von Vision AI ist es notwendig, beim Kauf ihr hochgeladenes Bild zu speichern. Diese Informationen werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert. Der Anbieter dieser Seite hat keinen Einfluss auf diese Datenübertragung.
                        <br />Die Nutzung von Vision AI erfolgt im Interesse einer automatischen Blockierung von unangemessenen Inhalten, welche in der von uns angebotenen App RichList angezeigt werden. Dies stellt ein berechtigtes Interesse im Sinne der Richlinien des App Stores von Apple und des Play Stores von Google da.
                        <br />Mehr Informationen zum Umgang mit Nutzerdaten finden Sie in der Datenschutzerklärung von Google: https://www.google.de/intl/de/policies/privacy/.

                        <br /><br />18. Kontaktdaten des Verantwortlichen:
                        <br />info(at)richlist.net
                    </p>
                </div>
            </div>
        );
    }
}