import React, { Component } from 'react';

export default class Terms extends Component {
    render() {
        return (
            <div className="container">
                <div className="termctn">
                    <p className="legal language">
                        Die deutsche Version finden Sie <a className="linkcolor" href="agb">hier</a>
                    </p>
                    <br />
                    <p className="header">
                        RichList Term of Service <br />                        
                    </p>
                    <p className="terms">Last Updated on August 10, 2019</p>
                    <p className="terms">
        
                        <b>Overview.</b><br />
                        Welcome to the mobile app RichList (“app”) and its website richlist.net (“site”). Throughout the site, the “we”, “us”, “our”, “Services”, “RichList” refer to the RichList site, app and all corresponding services. And all user of these Services will refer as “User”.<br />
                        <br />
                        Please read the following Terms of Service carefully before installing, downloading and/or using the app or using this site. By visiting our site and/or using our services/app, you agree to be bound by the following terms and conditions (“Terms of Service”, “Terms”), including those additional terms and conditions and policies referenced herein and/or available by hyperlink. These Terms of Service apply to all Users of the app, including without limitation Users who are browsers, customers, tippers, and/or contributors of content.<br />
                        If you do not agree to be bound by these Terms please do not access or use RichList.<br />
                        <br />
                        The headings used in this Agreement are included for convenience only and will not limit or otherwise affect these Terms.<br />
                        <br />
                        <b>Information.</b><br />
                        We are not responsible if information made available on RichList is not accurate, complete, or current. RichList may contain certain historical information. Historical information, necessarily, is not current and is provided for your reference only. The material on RichList is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or timelier sources of information. Any reliance on the material on RichList is at your own risk. We reserve the right to modify the contents of RichList at any time, but we have no obligation to update any information RichList. You agree that it is your responsibility to monitor changes to RichList. Your use of the Content, or any part thereof, is made solely at your own risk and responsibility.<br />
                        <br />
                        <b>Modification. </b><br />
                        Any new features or tools which are added to the Services shall also be subject to the Terms of Service. You can review the most current version of the Terms of Service at any time on this page. We reserve the right to update, change or replace any part of these Terms of Service by posting updates and/or changes to our website. It is your responsibility to check this page periodically for changes. Your continued use of or access to the Services following the posting of any changes constitutes acceptance of those changes.<br />
                        <br />
                        <b>Our Rights.</b><br />
                        We reserve these rights, which we may exercise at any time and in our sole discretion, and without liability or notice to you (except where prohibited by applicable law): (a) we may change parts or all of the Services and their functionality; (b) we may suspend or discontinue parts or all of the Services; (c) we may terminate, suspend, restrict or disable your access to or use of parts or all of the Services; (d) we may terminate, suspend, restrict or disable access to your Account or parts; and (e) we may change our eligibility criteria to use the Services (and if such eligibility criteria changes are prohibited by law where you live, we may revoke your right to use the Services in that jurisdiction).<br />
                        <br />
                        <b>Ability to Accept Terms.</b><br />
                        The Services are available only to individuals who (a) are either (i) for EU residents at least sixteen (16) years old, and (ii) for US residents at least thirteen (13) years old; (iii) or if an individual is located in any other GEO, you are above the age defined as "child" under applicable laws in your jurisdiction; and (b) possess the legal capacity to enter into these Terms and to form a binding agreement under any applicable law, or have received the required consent from their legal guardian to enter into these Terms, and provided that if you are between the ages of 13 and 18, you represent that your legal guardian has reviewed and agreed to these Terms, including the Privacy Policy. Therefore, you hereby represent that you possess the legal authority to enter into these Terms, to form a binding agreement under any applicable law, to use the Services in accordance with these Terms, and to fully perform your obligations hereunder. Individuals under a certain age who have the express consent of their legal guardian may nonetheless be prohibited from participating in particular Services.<br />
                        <br />
                        <b>Services Access. </b><br />
                        For such time as these Terms are in effect, we hereby grant you permission to visit and use the Services provided that you comply with these Terms and applicable law.<br />
                        We reserve the right to refuse service to anyone for any reason at any time.<br />
                        <br />
                        <b>Restrictions. </b><br />
                        You shall not: (i) copy, distribute or modify any part of the Services without our prior written authorization; (ii) use, modify, create derivative works of, transfer (by sale, resale, license, sublicense, download or otherwise), reproduce, distribute, display or disclose Content (defined below), except as expressly authorized herein; (iii) disrupt servers or networks connected to the Services; (iv) use or launch any automated system (including without limitation, 'bots' and 'spiders') to access or use the Services; and/or (v) circumvent, disable or otherwise interfere with security-related features of the Services or features that prevent or restrict use or copying of any Content or that enforce limitations on use of the Services.<br />
                        <br />
                        <b>Account. </b><br />
                        In order to use the App, you have a randomly generated unique key (“Key”) to get identified. You agree not to share your Key or use they Key of another User. We reserve the right to delete any account information without advance notice. If you lose your Key there might be no way to retrieve your account information or your Key. You are solely responsible for the activity that occurs with your Key, and you must keep your Key secure. If you wish to delete your Key and corresponding data you may do it by sending an email request to RichList at info(at)richlist.net. If you can provide enough evidence of past transactions, we will deal with your request in accordance with applicable law.<br />
                        <br />
                        <b>Payment. </b><br />
                        RichList enables User to transfer money to us (“Payment”) and you acknowledge that you are not receiving any goods/services in return for this Payment. Payments may be submitted by Users and processed through various third party payment processing services (“Payment Providers”), and additional terms may apply to such payments. In addition to these Terms, you agree that the terms and conditions of such Payment Providers shall apply to the online payments. Due to currency exchange discrepancy from our API and our Payment Providers API the total charge to the tipper may off by a minimal amount. We reserve the right, at any time and for any reason, at our sole discretion, to: (1) change our available our Payment Providers; (2) eliminate the option to execute payments; and (3) to limit the number and/or frequency of payment transactions permitted via the App.<br />
                        RichList shall in no event be responsible or liable for: (A) the availability and/or operation of any Payment Provider; (B) the acknowledgement or fulfillment of any transactions in our Services (C) any unfulfilled payment transaction which results from incorrect payment information provided by the User or which is made not in accordance with these terms.<br />
                        By offering a Payment, you, as a User hereby confirm that: (i) you are using a valid credit card which is owned by you for the Payment and providing complete and accurate information in connection with the transaction; and (ii) no goods or services have been offered to you in consideration for the Payment and the Payment has not been solicited in any way. All Payments are non-refundable and cannot be withdrawn or charged back by Users. Users hereby confirm and acknowledge that Payments shall not be subject to or conditioned upon any consideration or benefit, including without limitation the performance of RichList.<br />
                        <br />
                        <b>Intellectual Property Rights.</b><br />
                        1. End User License. Subject to the terms and conditions of these Terms, we hereby grant you a personal, revocable, non-exclusive, non-sublicensable, non-assignable, non-transferable license (“License”) to: (i) download, install and use the App and/or Plug-In (as applicable) on a computer, mobile telephone or any other device you are using to access the Service (the “Device”); and (ii) access and use the Services on that Device in accordance with these Terms.<br />
                        2. Content and Marks. The (i) content on the Services, including without limitation, the text, descriptions, products, software, graphics, photos, sounds, videos, interactive features, and services(collectively, the “Materials”), (ii) and User Submissions, as defined below (together with the Materials, the “Content”) are the property of RichList and/or its licensors and may be protected by applicable copyright or other intellectual property laws and treaties. All other trademarks, service marks, and logos used in the Services are the trademarks, service marks, or logos of their respective owners. We reserve all rights not expressly granted in and to the Services and the Content.<br />
                        3. License Restrictions. You agree not to, and shall not permit any third party to: (i) sublicense, redistribute, sell, lease, lend or rent the Services; (ii) make the Services available over a network where it could be used by multiple devices owned or operated by different people at the same time; (iii) disassemble, reverse engineer, decompile, decrypt, or attempt to derive the source code of, the Services; (iv) copy, modify, improve, or create derivative works of the Services or any part thereof; (v) circumvent, disable or otherwise interfere with security-related features of the Services or features that prevent or restrict use or copying of any content or that enforce limitations on use of the Services; (vi) remove, alter or obscure any proprietary notice or identification, including copyright, trademark, patent or other notices, contained in or displayed on or via the Services; (vii) use any communications systems provided by the App to send unauthorized and/or unsolicited commercial communications; (viii) use the RichList name or logo without our prior written consent; and/or (ix) use the Services to violate any applicable laws, rules or regulations, or for any unlawful, harmful, irresponsible, or inappropriate purpose, or in any manner that breaches this Agreement.<br />
                        <br />
                        <b>User Submissions.</b><br />
                        You understand that your content, may be transferred unencrypted and involve transmissions over various networks and changes to conform and adapt to technical requirements of connecting networks or devices.<br />
                        1. Responsibility.The Services permit the submission, hosting, sharing and publishing of Content by you and other users (“User Submissions”). You understand that whether or not such User Submissions are published, we do not guarantee any confidentiality with respect to any User Submissions. You shall be solely responsible for your User Submissions and the consequences of posting, publishing or uploading them. We have complete discretion whether to publish your User Submissions and we reserve the right in our sole discretion and without further notice to you, to monitor, censor, edit, remove, delete, and/or remove any and all Content posted on the Services (including User Submissions) at any time and for any reason.<br />
                        2. Ownership. You represent and warrant that you own or have the necessary rights and permissions to use and authorize RichList to use all Intellectual Property Rights (defined below) in and to your User Submissions, and to enable inclusion and use thereof as contemplated by the Services and these Terms. Unless the User Submissions are separately referred to, all references herein to Content shall include references to User Submissions.”Intellectual Property Rights” means any and all rights, titles and interests, whether foreign or domestic, in and to any and all trade secrets, patents, copyrights, service marks, trademarks, know-how, or similar intellectual property rights, as well as any and all moral rights, rights of privacy, publicity and similar rights of any type under the laws or regulations of any governmental, regulatory, or judicial authority, foreign or domestic. You retain all of your ownership rights in and to your User Submissions.<br />
                        3. License to User Submissions. By submitting the User Submissions to RichList, you hereby grant RichList and partners a worldwide, irrevocable, non-exclusive, royalty-free, perpetual, sublicenseable and transferable license to use, edit, archive, transmit, broadcast, sell, translate, publish, reproduce, distribute, prepare derivative works of, display, and perform the User Submissions and your name, likeness and other identifying information part of a User Submission, and the usage in connection with the Services and RichList's business, including without limitation for developing, manufacturing, marketing products, publishing and redistributing part or all of your User Submissions (and derivative works thereof) in any form, media, software, or technology of any kind now known or developed in the future and you hereby waive any moral rights in your User Submissions, to the extent permitted by law. You also hereby grant each user of the Services or other user of the User Submission a non-exclusive right to use, reproduce, distribute, prepare derivative works of, display and perform such User Submissions, all in accordance with these Terms.<br />
                        4. Prohibited Content. You agree that you will not display, post, submit, publish, upload or transmit a User Submission that: (i) is unfair or deceptive under the consumer protection laws of any jurisdiction; (ii) is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights; (iii) creates a risk to a person’s safety or health, creates a risk to public safety or health, compromises national security, or interferes with an investigation by law enforcement; (iv) impersonates another person; (v) promotes illegal drugs, violates export control laws, relates to illegal gambling, or illegal arms trafficking; (vi) is unlawful, defamatory, libelous, threatening, pornographic, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, gives rise to civil liability, violates any law, or is inappropriate; (vii) involves theft or terrorism; (viii)  includes a photograph or video of another person that you have posted without that person's consent; (ix) violates or attempts to violate the privacy rights, publicity rights, intellectual property rights, contract rights, or any other rights of any person; or (x) is otherwise malicious or fraudulent.<br />
                        5. Exposure. You understand and acknowledge that when accessing and using the Services: (i) you will be exposed to User Submissions from a variety of sources, and that RichList is not responsible for the accuracy, usefulness, safety, or Intellectual Property Rights of, or relating to, such User Submissions; and (ii) you may be exposed to User Submissions that are inaccurate, offensive, indecent, or objectionable. You hereby agree to waive, and hereby do waive, any legal or equitable rights or remedies you may have against RichList with respect to (i) and (ii) herein.<br />
                        <br />
                        <b>Copyright.</b><br />
                        We comply with copyright law, and respond to complaints about copyright infringements. We respect the intellectual property of others and ask that you do too. We respond to notices of alleged copyright infringement if they comply with the law. We reserve the right to delete or disable content alleged to be infringing, and to terminate Accounts of repeat infringers without any refunds. For any complaints contact us at info(at)richlist.net.<br />
                        <br />
                        <b>Links.</b><br />
                        The Services may contain links, and may enable you to post content, to third party websites that are not owned or controlled by RichList. We are not affiliated with, have no control over, and assume no responsibility for the content, privacy policies, or practices of, any third party websites. You: (i) are solely responsible and liable for your use of and linking to third party websites and any content that you may send or post to a third party website; and (ii) expressly release RichList from any and all liability arising from your use of any third party website. Accordingly, we encourage you to read the terms and conditions and privacy policy of each third party website that you may choose to visit.<br />
                        <br />
                        RichList permits you to link to the Site provided that: (i) you link to but do not replicate any page on the Site; (ii) the hyperlink text shall accurately describe the Content as it appears on the Site; (iii) you shall not misrepresent your relationship with RichList or present any false information about RichList and shall not imply in any way that we are endorsing any services or products, unless we have given you our express prior consent; (iv) you shall not link from a website which prohibits linking to third parties; (v) such Third Party Website does not contain content that (a) is offensive or controversial (both at our discretion), or (b) infringes any intellectual property, privacy rights, or other rights of any person or entity; and/or (vi) you, and your website, comply with these Terms and applicable law.<br />
                        <br />
                        <b>Privacy. </b><br />
                        We will use any personal information that we may collect or obtain in connection with the Services in accordance with our privacy policy which is available at www.richlist.net/privacy. You agree that we may use personal information that you provide or make available to us in accordance with the privacy policy.<br />
                        <br />
                        <b>Warranty Disclaimers.</b><br />
                        1. This section applies whether or not the services provided under the Services are for payment. Applicable law may not allow the exclusion of certain warranties, so to that extent certain exclusions set forth herein may not apply.<br />
                        2. THE SERVICES ARE PROVIDED ON AN 'AS IS' AND 'AS AVAILABLE' BASIS, AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. RICHLIST HEREBY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND THOSE ARISING BY STATUTE OR FROM A COURSE OF DEALING OR USAGE OF TRADE. RICHLIST DOES NOT GUARANTEE THAT THE SERVICES WILL BE FREE OF BUGS, SECURITY BREACHES, OR VIRUS ATTACKS. THE SERVICES MAY OCCASIONALLY BE UNAVAILABLE FOR ROUTINE MAINTENANCE, UPGRADING, OR OTHER REASONS. YOU AGREE THAT RICHLIST WILL NOT BE HELD RESPONSIBLE FOR ANY CONSEQUENCES TO YOU OR ANY THIRD PARTY THAT MAY RESULT FROM TECHNICAL PROBLEMS OF THE INTERNET, SLOW CONNECTIONS, TRAFFIC CONGESTION OR OVERLOAD OF OUR OR OTHER SERVERS. WE DO NOT WARRANT, ENDORSE OR GUARANTEE ANY CONTENT, PRODUCT, OR SERVICE THAT IS FEATURED OR ADVERTISED ON THE SERVICES BY A THIRD PARTY.<br />
                        3. RICHLIST DOES NOT WARRANT, ENDORSE OR GUARANTEE ANY CONTENT THAT APPEARS IN A USER SUBMISSION, AND DOES NOT MAKE ANY REPRESENTATION OR WARRANTY WITH RESPECT TO, AND DISCLAIMS ALL LIABILITY FOR, ANY SUCH CONTENT.<br />
                        4. YOU SPECIFICALLY ACKNOWLEDGE THAT RICHLIST SHALL NOT BE RESPONSIBLE FOR THE USER SUBMISSIONS OR CONDUCT (INCLUDING DEFAMATORY, OFFENSIVE, ILLEGAL, OR NEGLIGENT CONDUCT) OF ANY SERVICES USER AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU.<br />
                        5. YOUR RELIANCE ON, OR USE OF, ANY USER SUBMISSION, OR INTERACTION WITH ANY SERVICES USER OR OWNER, IS AT YOUR SOLE RISK. IF YOU HAVE A DISPUTE WITH ANY SERVICES USER OR OWNER IN CONNECTION WITH THE SERVICES OR ANY USER SUBMISSION, YOU AGREE THAT RICHLIST IS NOT LIABLE FOR ANY CLAIMS OR DAMAGES ARISING OUT OF OR CONNECTED WITH SUCH A DISPUTE. RICHLIST RESERVES THE RIGHT, BUT HAS NO OBLIGATION, TO MONITOR ANY SUCH DISPUTE.<br />
                        6. EXCEPT AS EXPRESSLY STATED IN OUR PRIVACY POLICY, RICHLIST DOES NOT MAKE ANY REPRESENTATIONS, WARRANTIES OR CONDITIONS OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE SECURITY OF ANY INFORMATION YOU MAY PROVIDE OR ACTIVITIES YOU ENGAGE IN DURING THE COURSE OF YOUR USE OF THE SERVICES.<br />
                        <br />
                        <b>Limitation of Liability.</b><br />
                        TO THE FULLEST EXTENT PERMISSIBLE BY LAW, RICHLIST SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, EXEMPLARY, SPECIAL, CONSEQUENTIAL, OR INCIDENTAL DAMAGES OF ANY KIND, OR FOR ANY LOSS OF DATA, REVENUE, PROFITS OR REPUTATION, ARISING UNDER THESE TERMS OR OUT OF YOUR USE OF, OR INABILITY TO USE, THE SERVICES, EVEN IF RICHLIST HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR LOSSES. Some jurisdictions do not allow the limitation or exclusion of liability for incidental or consequential damages, in such jurisdictions, our liability shall be limited to the maximum extent permitted by law. <br />
                        <br />
                        <b>Indemnity. </b><br />
                        You agree to defend, indemnify and hold harmless RichList and our affiliates, and our respective officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs and expenses (including but not limited to attorney's fees) arising from: (i) your use of, or inability to use, the Services; (ii) your User Submissions; (iii) your interaction with any Services user; or (iv) your violation of these Terms.<br />
                        <br />
                        <b>Updates and Upgrades. </b><br />
                        We may from time to time provide updates or upgrades to the App or Site (each a “Revision”), but are not under any obligation to do so. Such Revisions will be supplied according to our then-current policies, which may include automatic updating or upgrading without any additional notice to you. You consent to any such automatic updating or upgrading of the App or Site. All references herein to the App and Site shall include Revisions thereto. This Agreement shall govern any Revisions that replace or supplement the original App or Site, unless the Revision is accompanied by a separate license agreement which will govern the Revision.<br />
                        <br />
                        <b>Third Party Open Source Software. </b><br />
                        Portions of the Services may include third party or open source software that is subject to third party terms and conditions ('Third Party Terms'). Such third party specific license terms and the accompanying copyright. We are not responsible for any such software. If there is a conflict between any Third Party Terms and the terms of this Terms, then the Third Party Terms shall prevail but solely in connection with the related third party open source software.<br />
                        <br />
                        <b>Term and Termination. </b><br />
                        These Terms are effective until terminated by RichList or you. RichList, in its sole discretion, has the right to terminate these Terms and/or your access to the Services, or any part thereof, immediately at any time and with or without cause (including, without any limitation, for a breach of these Terms). RichList shall not be liable to you or any third party for termination of the Services, or any part thereof. If you object to any term or condition of these Terms, or any subsequent modifications thereto, or become dissatisfied with the Services in any way, your only recourse is to immediately discontinue use of the Services. Upon termination of these Terms, you shall cease all use of the Services. This Section and Sections “Intellectual Property Rights”, “License to User Submissions”, “Privacy”, ‎”Warranty Disclaimers”, ‎”Limitation of Liability”, “Indemnity”, and ‎”Independent Contractors” to “General” shall survive termination of these Terms.<br />
                        <br />
                        <b>Independent Contractors. </b><br />
                        You and RichList are independent contractors. Nothing in these Terms creates a partnership, joint venture, agency, or employment relationship between you and RichList. You must not under any circumstances make, or undertake, any warranties, representations, commitments or obligations on behalf of RichList.<br />
                        <br />
                        <b>Assignment. </b><br />
                        These Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you but may be assigned by RichList without restriction or notification to you. Any prohibited assignment shall be null and void.<br />
                        <br />
                        <b>Governing Law. </b><br />
                        RichList reserves the right to discontinue or modify any aspect of the Services at any time. These Terms and the relationship between you and RichList shall be governed by and construed in accordance with the laws of the country Germany, without regard to its principles of conflict of laws.<br />
                        <br />
                        <b>General. </b><br />
                        These Terms shall constitute the entire agreement between you and RichList concerning the Services. If any provision of these Terms is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms, which shall remain in full force and effect. No waiver of any term of these Terms shall be deemed a further or continuing waiver of such term or any other term, and a party's failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision.<br />
                    </p>
                </div>
            </div>
        );
    }
}
