module.exports = {
  en: {
    tos1: "By using the pay button you confirm that you have read, understood and accepted our",
    tos2: "Terms of Service",
    tos3: "and",
    tos4: "Privacy Policy",
    tos5: ".",
    tos6: "Legal notice",
    tos7: "Terms of Service",
    tosTermsLink: "https://www.richlist.net/terms.html",
    tosPrivacyLink: "https://www.richlist.net/privacy.html",
    withdraw1: "I expressly agree to the execution of the contract before the expiration of the withdrawal period. I have acknowledged that my right of withdrawal expires when the contract is executed.",
    withdraw2: "Withdrawal Policy",
    withdrawLink: "https://www.richlist.net/withdraw.html",
    tosLegalLink: "https://www.richlist.net/legalnotice.html",
    pay: "Pay now",
    name: "Enter Name",
    uniqueKey: "Set a payment key (optional)",
    email: "Enter E-Mail",
    message: "Message (optional)",
    instagram: "Your Instagram (optional)",
    twitter: "Your Twitter (optional)",
    snapchat: "Your Snapchat (optional)",
    amount: "Amount in $",
    makeA: "Make a payment",
    yes: "Yes!",
    new: "Delete",
    toLegal: "/legal",
    toTerms: "/terms",
    toPrivacy: "/privacy"
  },
  de: {
    tos1: "Mit der Benutzung des bezahlen Buttons bestätigen Sie, dass Sie die",
    tos2: "Allgemeine Geschäftsbedingungen",
    tos3: "und",
    tos4: "Datenschutzerklärung",
    tos5: " gelesen, verstanden und akzeptiert haben.",
    tos6: "Impressum",
    tos7: "AGB",
    tosTermsLink: "https://www.richlist.net/agbs.html",
    tosPrivacyLink: "https://www.richlist.net/datenschutz.html",
    withdraw1: "Ich stimme der Ausführung des Vertrages vor Ablauf der Widerrufsfrist ausdrücklich zu. Ich habe zur Kenntnis genommen, dass mein Widerrufsrecht mit Beginn der Ausführung des Vertrags erlischt.",
    withdraw2: "Widerrufsbelehrung",
    tosLegalLink: "https://www.richlist.net/impressum.html",
    withdrawLink: "https://www.richlist.net/widerruf.html",
    pay: "Kostenpflichtig bezahlen",
    name: "Name eingeben",
    email: "E-Mail eingeben",
    message: "Nachricht (optional)",
    instagram: "Dein Instagram (optional)",
    twitter: "Dein Twitter (optional)",
    snapchat: "Dein Snapchat (optional)",
    amount: "Betrag in $",
    makeA: "Tätige eine Zahlung",
    yes: "Nehm' ich!",
    uniqueKey: "Zahlungsschlüssel (optional)",
    new: "Löschen",
    toLegal: "/impressum",
    toTerms: "/agb",
    toPrivacy: "/datenschutz"
  }
};