module.exports = {
  en: {
    tos1: "By using the pay button you confirm that you have read, understood and accepted our",
    tos2: "Terms of Service",
    tos3: "and",
    tos4: "Privacy Policy",
    tos5: ".",
    tos6: "Legal notice",
    tos7: "Terms of Service",
    tosTermsLink: "https://www.richlist.net/terms",
    tosPrivacyLink: "https://www.richlist.net/privacy",
    withdraw1: "I expressly agree to the execution of the contract before the expiration of the withdrawal period. I have acknowledged that my right of withdrawal expires when the contract is executed.",
    withdraw2: "Withdrawal Policy",
    withdrawLink: "https://www.richlist.net/withdraw",
    tosLegalLink: "https://www.richlist.net/legal",
    pay: "Pay now",
    name: "Enter Name",
    uniqueKey: "Set a payment key (optional)",
    email: "Enter E-Mail",
    message: "Message (optional)",
    instagram: "Your Instagram (optional)",
    twitter: "Your Twitter (optional)",
    snapchat: "Your Snapchat (optional)",
    tiktok: "Your Tiktok (optional)",
    amount: "Amount in $",
    makeA0: "Make a payment", 
    makeA1: "here",
    makeA2: "to get on the RichList and download the App to see what is going on!",
    yes: "Yes!",
    new: "Delete",
    toLegal: "/legal",
    toTerms: "/terms",
    toPrivacy: "/privacy",
    cookies1: "To make Medium work, we log user data. By using Medium, you agree to our ",
    cookies2: ", including cookie policy.",
    buttonText: "I understand",
    declineButtonText: "I decline",
    support: "If you have any questions about you payment, other payment methods or a collaboration, feel free to contact us via Email info(at)richlist.net.",
    method: "Payment method",
    paymentkey: "Payment key",
    paymentInfo: "After your first payment you will receive an unique payment key which you can provide in your next payment to accumulate your payments.",
    paypalLimit: "PayPal is only avaiable for payments below $2000",
    makeAPayment1: "Checkout area",
    makeAPayment2: "Make your first payment!",
    makeAPayment3: "Is it you first or an aditional payment?",
    firstTime: "First payment",
    nextTime: "Additional payment"
  },
  de: {
    tos1: "Mit der Benutzung des bezahlen Buttons bestätigen Sie, dass Sie die",
    tos2: "Allgemeine Geschäftsbedingungen",
    tos3: "und",
    tos4: "Datenschutzerklärung",
    tos5: " gelesen, verstanden und akzeptiert haben.",
    tos6: "Impressum",
    tos7: "AGB",
    tosTermsLink: "https://www.richlist.net/agb",
    tosPrivacyLink: "https://www.richlist.net/datenschutz",
    withdraw1: "Ich stimme der Ausführung des Vertrages vor Ablauf der Widerrufsfrist ausdrücklich zu. Ich habe zur Kenntnis genommen, dass mein Widerrufsrecht mit Beginn der Ausführung des Vertrags erlischt.",
    withdraw2: "Widerrufsbelehrung",
    tosLegalLink: "https://www.richlist.net/impressum",
    withdrawLink: "https://www.richlist.net/widerruf",
    pay: "Kostenpflichtig bezahlen",
    name: "Name eingeben",
    email: "E-Mail eingeben",
    message: "Nachricht (optional)",
    instagram: "Dein Instagram (optional)",
    twitter: "Dein Twitter (optional)",
    snapchat: "Dein Snapchat (optional)",
    tiktok: "Dein Tiktok (optional)",
    amount: "Betrag in $",
    makeA0: "Tätige",
    makeA1: "hier",
    makeA2: "eine Zahlung, um auf die RichList zu kommen und lade die App herunter, um immer auf dem neusten Stand zu bleiben!",
    yes: "Nehm' ich!",
    uniqueKey: "Zahlungsschlüssel (optional)",
    new: "Löschen",
    toLegal: "/impressum",
    toTerms: "/agb",
    toPrivacy: "/datenschutz",
    cookies1: "Damit RichList funktioniert, loggen wir Nutzerdaten. Wenn du RichList benutzt, stimmst du unserer ",
    cookies2: ", inklusive unseren Cookierichtlinien zu.",
    buttonText: "Ich verstehe",
    declineButtonText: "Ablehnen",
    support: "Falls Sie Fragen zu Ihrer Zahlung, weiteren Zahlungsmethoden oder einer Kollaboration haben, schreiben Sie uns gerne eine Email an info(at)richlist.net.",
    method: "Zahlungsmethode",
    paymentKey: "Zahlungsschlüssel",
    paymentInfo: "Nach Ihrer ersten Zahlung erhalten Sie einen individuellen Zahlungsschlüssel, den Sie bei Ihrer nächsten Zahlung angeben können, um Ihre Zahlungen zu summieren.",
    paypalLimit: "PayPal ist nur bei Zahlungen von unter 2.000$ verfügbar",
    makeAPayment1: "Checkout Bereich",
    makeAPayment2: "Mache deine erste Zahlung!",
    makeAPayment3: "Ist es deine erste oder eine erneute Zahlung?",
    firstTime: "Erste Zahlung",
    nextTime: "Erneut bezahlen"
  }
};