module.exports = {
  en: {
    tos1: "By using the pay button you confirm that you have read, understood and accepted our",
    tos2: "Terms of Service",
    tos3: "and",
    tos4: "Privacy Policy",
    tos5: ".",
    tos6: "Legal notice",
    tos7: "Terms of Service",
    tos8: "Cookies",
    tosTermsLink: "https://www.richlist.net/terms",
    tosPrivacyLink: "https://www.richlist.net/privacy",
    withdraw1: "I expressly agree to the execution of the contract before the expiration of the withdrawal period. I have acknowledged that my right of withdrawal expires when the contract is executed.",
    withdraw2: "Withdrawal Policy",
    withdrawLink: "https://www.richlist.net/withdraw",
    tosLegalLink: "https://www.richlist.net/legal",
    toCookie: "https://www.richlist.net/cookies/en",
    pay: "Pay now",
    name: "Enter Name",
    uniqueKey: "Set a payment key (optional)",
    email: "Enter E-Mail",
    message: "Message (optional)",
    instagram: "Your Instagram (optional)",
    twitter: "Your Twitter (optional)",
    snapchat: "Your Snapchat (optional)",
    tiktok: "Your Tiktok (optional)",
    amount: "Amount in $",
    makeA0: "Make a payment", 
    makeA1: "here",
    makeA2: "to get on the RichList and download the App to see what is going on!",
    yes: "Yes!",
    new: "Delete",
    toLegal: "/legal",
    toTerms: "/terms",
    toPrivacy: "/privacy",
    cookies1: "To make Medium work, we log user data. By using Medium, you agree to our ",
    cookies2: ", including cookie policy.",
    buttonText: "OK",
    declineButtonText: "I decline",
    support: "If you have any questions about you payment, other payment methods or a collaboration, feel free to contact us via Email info(at)richlist.net.",
    method: "Payment method",
    uniqueKeyShort: "Payment key",
    uniqueKeyLong: "After your first payment you will receive an unique payment key in you confirmation email which you can provide in your next payment to accumulate your payments.",
    paypalLimit: "PayPal is only avaiable for payments below $2000",
    makeAPayment1: "Checkout area",
    makeAPayment2: "Make your first payment!",
    makeAPayment3: "Enter your payment key!",
    firstTime: "First payment",
    nextTime: "Additional payment",
    alreadyPaid: "Total paid amount: ",
    instagramShort: "Instagram",
    instagramLong: "Enter your Instagram name so other users can find you on Instagram.",
    twitterShort: "Twitter",
    twitterLong: "Enter your Twitter name so other users can find you on Twitter.",
    tiktokShort: "TikTok",
    tiktokLong: "Enter your TikTok name so other users can find you on TikTok.",
    snapchatShort: "Snapchat",
    snapchatLong: "Enter your Snapchat name so other users can find you on Snapchat.",
    messageShort: "Personal message",
    messageLong: "Provide a personal message which other users will see in your RichList profile.",
    amountShort: "Amount",
    amountLong: "Enter the amount of money you want to spend.",
    uniqueNameShort: "Username",
    uniqueNameLong: "Enter an unique username.",
    mailShort: "Email",
    mailLong: "Enter your email. You will receive a confirmation email after your purchase.",
    notExisting: "User doesn't exist!",
    toastTime: "Just now",
    toastText: "Tap on the images and names!"
  },
  de: {
    tos1: "Mit der Benutzung des bezahlen Buttons bestätigen Sie, dass Sie die",
    tos2: "Allgemeine Geschäftsbedingungen",
    tos3: "und",
    tos4: "Datenschutzerklärung",
    tos5: " gelesen, verstanden und akzeptiert haben.",
    tos6: "Impressum",
    tos7: "AGB",
    tos8: "Cookies",
    tosTermsLink: "https://www.richlist.net/agb",
    tosPrivacyLink: "https://www.richlist.net/datenschutz",
    toCookie: "https://www.richlist.net/cookies/de",
    withdraw1: "Ich stimme der Ausführung des Vertrages vor Ablauf der Widerrufsfrist ausdrücklich zu. Ich habe zur Kenntnis genommen, dass mein Widerrufsrecht mit Beginn der Ausführung des Vertrags erlischt.",
    withdraw2: "Widerrufsbelehrung",
    tosLegalLink: "https://www.richlist.net/impressum",
    withdrawLink: "https://www.richlist.net/widerruf",
    pay: "Kostenpflichtig bezahlen",
    name: "Name eingeben",
    email: "E-Mail eingeben",
    message: "Nachricht (optional)",
    instagram: "Dein Instagram (optional)",
    twitter: "Dein Twitter (optional)",
    snapchat: "Dein Snapchat (optional)",
    tiktok: "Dein Tiktok (optional)",
    amount: "Betrag in $",
    makeA0: "Tätige",
    makeA1: "hier",
    makeA2: "eine Zahlung, um auf die RichList zu kommen und lade die App herunter, um immer auf dem neusten Stand zu bleiben!",
    yes: "Nehm' ich!",
    uniqueKey: "Zahlungsschlüssel (optional)",
    new: "Löschen",
    toLegal: "/impressum",
    toTerms: "/agb",
    toPrivacy: "/datenschutz",
    cookies1: "Damit RichList funktioniert, loggen wir Nutzerdaten. Wenn du RichList benutzt, stimmst du unserer ",
    cookies2: ", inklusive unseren Cookierichtlinien zu.",
    buttonText: "OK",
    declineButtonText: "Ablehnen",
    support: "Falls Sie Fragen zu Ihrer Zahlung, weiteren Zahlungsmethoden oder einer Kollaboration haben, schreiben Sie uns gerne eine Email an info(at)richlist.net.",
    method: "Zahlungsmethode",
    uniqueKeyShort: "Zahlungsschlüssel",
    uniqueKeyLong: "Nach Ihrer ersten Zahlung erhalten Sie einen individuellen Zahlungsschlüssel per E-Mail, den Sie bei Ihrer nächsten Zahlung angeben können, um Ihre Zahlungen zu summieren.",
    paypalLimit: "PayPal ist nur bei Zahlungen von unter 2.000$ verfügbar",
    makeAPayment1: "Checkout Bereich",
    makeAPayment2: "Mache deine erste Zahlung!",
    makeAPayment3: "Gib deinen Zahlungsschlüssel ein!",
    firstTime: "Erste Zahlung",
    nextTime: "Erneut bezahlen",
    alreadyPaid: "Bisher eingezahlt: ",
    instagramShort: "Instagram",
    instagramLong: "Hier können Sie ihren Instagram Namen angeben, damit andere Nutzer sie auf Instagram finden können.",
    twitterShort: "Twitter",
    twitterLong: "Hier können Sie ihren Twitter Namen angeben, damit andere Nutzer sie auf Twitter finden können.",
    tiktokShort: "TikTok",
    tiktokLong: "Hier können Sie ihren TikTok Namen angeben, damit andere Nutzer sie auf TikTok finden können.",
    snapchatShort: "Snapchat",
    snapchatLong: "Hier können Sie ihren Snapchat Namen angeben, damit andere Nutzer sie auf Snapchat finden können.",
    messageShort: "Persönliche Nachricht",
    messageLong: "Hier können Sie eine persönliche Nachricht angeben, die anderen Nutzern auf RichList angezeigt wird.",
    amountShort: "Betrag",
    amountLong: "Geben Sie hier den Betrag ein, den Sie auf RichList ausgeben möchten.",
    uniqueNameShort: "Benutzername",
    uniqueNameLong: "Geben Sie hier einen individuellen Benutzernamen ein.",
    mailShort: "E-Mail",
    mailLong: "Geben Sie hier Ihre E-Mail Adresse ein, damit sie eine Bestellbestätigung erhalten können.",
    notExisting: "Benutzer existiert nicht!",
    toastTime: "Jetzt",
    toastText: "Klicke auf die Bilder und Namen!"
  }
};